const now = 2024;
const myAge = now - 2003;
const yourAge = now - 2002;
console.log(myAge, yourAge);
console.log(myAge * 2, yourAge / 2);
console.log(myAge, yourAge, 2 ** 5);
//Assignment operator;
let x = 5;
x++;
console.log(x);
--x;
console.log(x);
x = x * x;
console.log(x);
console.log(myAge > yourAge);
console.log(myAge * 2, yourAge * 4);
x += 45;
console.log(x);
